Repository dkdace/dmgr-server, pull requests merged in 2023-01, with the labels that each got.

#47 #27 게임 인스턴스 / 매치메이킹 추가 완료
  src/main/java/com/kiwi/dmgr/Game.java
  src/main/java/com/kiwi/dmgr/GameMapList.java
  src/main/java/com/kiwi/dmgr/GameType.java
  src/main/java/com/kiwi/dmgr/GameUser.java
  src/main/java/com/kiwi/dmgr/Team.java
  src/main/java/com/kiwi/dmgr/match/MatchMaking.java
  src/main/java/com/kiwi/dmgr/match/MatchQueue.java
  src/main/java/com/kiwi/dmgr/match/RankRating.java
Labels: ➕ Feature/System

#49 chore: add lombok dependency
  pom.xml
Labels: ⚙ Chore

#46 Reflection cost fix (makeshift)
  src/main/java/com/dace/dmgr/gui/ItemBuilder.java
Labels: 🛠 Refactoring

#50 #45 GUI 관련 리팩토링 완료
  src/main/java/com/dace/dmgr/DMGR.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/event/listener/OnInventoryClick.java
  src/main/java/com/dace/dmgr/gui/Gui.java
  src/main/java/com/dace/dmgr/gui/ItemBuilder.java
  src/main/java/com/dace/dmgr/gui/PlayerSkull.java
  src/main/java/com/dace/dmgr/gui/item/ButtonItem.java
  src/main/java/com/dace/dmgr/gui/item/CombatItem.java
  src/main/java/com/dace/dmgr/gui/item/DisplayItem.java
  src/main/java/com/dace/dmgr/gui/item/IGuiItem.java
  src/main/java/com/dace/dmgr/gui/menu/ChatSoundMenu.java
  src/main/java/com/dace/dmgr/gui/menu/ChatSoundOption.java
  src/main/java/com/dace/dmgr/gui/menu/MainMenu.java
  src/main/java/com/dace/dmgr/gui/menu/Menu.java
  src/main/java/com/dace/dmgr/gui/menu/OptionMenu.java
  src/main/java/com/dace/dmgr/gui/menu/PlayerOption.java
  src/main/java/com/dace/dmgr/gui/menu/event/ChatSoundMenuEvent.java
  src/main/java/com/dace/dmgr/gui/menu/event/MainMenuEvent.java
  src/main/java/com/dace/dmgr/gui/menu/event/MenuEvent.java
  src/main/java/com/dace/dmgr/gui/menu/event/OptionMenuEvent.java
  src/main/java/com/dace/dmgr/gui/slot/ButtonSlot.java
  src/main/java/com/dace/dmgr/gui/slot/CommunicationSlot.java
  src/main/java/com/dace/dmgr/gui/slot/DisplaySlot.java
  src/main/java/com/dace/dmgr/gui/slot/ISlotItem.java
  src/main/java/com/dace/dmgr/lobby/ChatSound.java
  src/main/java/com/dace/dmgr/system/command/MenuCommand.java
  src/main/java/com/dace/dmgr/system/command/PlayerOptionCommand.java
Labels: 🛠 Refactoring
