Repository dkdace/dmgr-server, pull requests merged in 2023-03, with the labels that each got.

#51 #38 투사체 세부 시스템 구현 완료
  pom.xml
  src/main/java/com/dace/dmgr/combat/Bullet.java
  src/main/java/com/dace/dmgr/combat/BulletOption.java
  src/main/java/com/dace/dmgr/combat/Hitscan.java
  src/main/java/com/dace/dmgr/combat/HitscanOption.java
  src/main/java/com/dace/dmgr/combat/Projectile.java
  src/main/java/com/dace/dmgr/combat/ProjectileOption.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceA1.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java
  src/main/java/com/dace/dmgr/util/VectorUtil.java
Labels: ➕ Feature/System

#55 #54 전체 코드에 lombok 적용
  src/main/java/com/dace/dmgr/combat/action/Action.java
  src/main/java/com/dace/dmgr/combat/action/Skill.java
  src/main/java/com/dace/dmgr/combat/character/Character.java
  src/main/java/com/dace/dmgr/combat/character/arkace/Arkace.java
  src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/combat/entity/Hitbox.java
  src/main/java/com/dace/dmgr/combat/event/CombatUserEvent.java
  src/main/java/com/dace/dmgr/combat/event/combatuser/CombatUserActionEvent.java
  src/main/java/com/dace/dmgr/gui/PlayerSkull.java
  src/main/java/com/dace/dmgr/gui/item/ButtonItem.java
  src/main/java/com/dace/dmgr/gui/item/CombatItem.java
  src/main/java/com/dace/dmgr/gui/item/DisplayItem.java
  src/main/java/com/dace/dmgr/lobby/ChatSound.java
  src/main/java/com/dace/dmgr/lobby/User.java
  src/main/java/com/dace/dmgr/system/task/TaskTimer.java
Labels: 🛠 Refactoring

#62 Feat: 2중 탄창 무기 시스템 구현 (#56)
  src/main/java/com/dace/dmgr/combat/action/Swappable.java
  src/main/java/com/dace/dmgr/combat/action/Weapon.java
  src/main/java/com/dace/dmgr/combat/action/WeaponController.java
  src/main/java/com/dace/dmgr/event/listener/OnWeaponPreShoot.java
  src/main/java/com/dace/dmgr/system/Cooldown.java
Labels: ➕ Feature/System

#65 v0.2.1 완료
  pom.xml
  src/main/java/com/dace/dmgr/combat/CombatTick.java
  src/main/java/com/dace/dmgr/combat/action/Action.java
  src/main/java/com/dace/dmgr/combat/action/Skill.java
  src/main/java/com/dace/dmgr/combat/character/Character.java
  src/main/java/com/dace/dmgr/combat/character/arkace/Arkace.java
  src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/combat/entity/Hitbox.java
  src/main/java/com/dace/dmgr/combat/event/CombatUserEvent.java
  src/main/java/com/dace/dmgr/combat/event/combatuser/CombatUserActionEvent.java
  src/main/java/com/dace/dmgr/event/EventUtil.java
  src/main/java/com/dace/dmgr/event/MainEventManager.java
  src/main/java/com/dace/dmgr/gui/Gui.java
  src/main/java/com/dace/dmgr/gui/PlayerSkull.java
  src/main/java/com/dace/dmgr/gui/item/ButtonItem.java
  src/main/java/com/dace/dmgr/gui/item/CombatItem.java
  src/main/java/com/dace/dmgr/gui/item/DisplayItem.java
  src/main/java/com/dace/dmgr/gui/menu/ChatSoundOption.java
  src/main/java/com/dace/dmgr/gui/menu/Menu.java
  src/main/java/com/dace/dmgr/gui/menu/PlayerOption.java
  src/main/java/com/dace/dmgr/lobby/ChatSound.java
  src/main/java/com/dace/dmgr/lobby/User.java
  src/main/java/com/dace/dmgr/system/command/MenuCommand.java
  src/main/java/com/dace/dmgr/system/command/PlayerOptionCommand.java
  src/main/java/com/dace/dmgr/system/task/TaskTimer.java
  src/main/java/com/dace/dmgr/util/InventoryUtil.java
Labels: 🐞 Bug, 🛠 Refactoring, ⚙ Chore

#64 정조준 기능 구현
  src/main/java/com/dace/dmgr/combat/CombatTick.java
  src/main/java/com/dace/dmgr/combat/action/Aimable.java
  src/main/java/com/dace/dmgr/combat/action/WeaponController.java
  src/main/java/com/dace/dmgr/event/listener/OnPlayClientArmAnimation.java
Labels: ➕ Feature/System

#66 #60 테스트 기능 추가 완료
  src/main/java/com/dace/dmgr/DMGR.java
  src/main/java/com/dace/dmgr/system/command/SelectCharCommand.java
  src/main/java/com/dace/dmgr/system/command/test/DummyCommand.java
  src/main/java/com/dace/dmgr/system/command/test/SelectCharCommand.java
  src/main/resources/plugin.yml
Labels: 🧪 Test

#68 #67 전체 Lombok 적용 및 주석 수정 완료
  src/main/java/com/dace/dmgr/combat/Bullet.java
  src/main/java/com/dace/dmgr/combat/Combat.java
  src/main/java/com/dace/dmgr/combat/Hitscan.java
  src/main/java/com/dace/dmgr/combat/HitscanOption.java
  src/main/java/com/dace/dmgr/combat/Projectile.java
  src/main/java/com/dace/dmgr/combat/ProjectileOption.java
  src/main/java/com/dace/dmgr/combat/action/Action.java
  src/main/java/com/dace/dmgr/combat/action/ActionKeyMap.java
  src/main/java/com/dace/dmgr/combat/action/SkillController.java
  src/main/java/com/dace/dmgr/combat/action/Swappable.java
  src/main/java/com/dace/dmgr/combat/action/WeaponController.java
  src/main/java/com/dace/dmgr/combat/character/arkace/Arkace.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceA1.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceA2.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceP1.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceUlt.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java
  src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/combat/entity/Hitbox.java
  src/main/java/com/dace/dmgr/combat/entity/ICombatEntity.java
  src/main/java/com/dace/dmgr/combat/entity/TemporalEntity.java
  src/main/java/com/dace/dmgr/combat/event/combatuser/CombatUserActionEvent.java
  src/main/java/com/dace/dmgr/gui/ItemBuilder.java
  src/main/java/com/dace/dmgr/gui/item/ButtonItem.java
  src/main/java/com/dace/dmgr/gui/item/CombatItem.java
  src/main/java/com/dace/dmgr/gui/item/IGuiItem.java
  src/main/java/com/dace/dmgr/gui/menu/ChatSoundOption.java
  src/main/java/com/dace/dmgr/gui/menu/Menu.java
  src/main/java/com/dace/dmgr/gui/menu/PlayerOption.java
  src/main/java/com/dace/dmgr/lobby/User.java
  src/main/java/com/dace/dmgr/lobby/UserConfig.java
  src/main/java/com/dace/dmgr/system/Cooldown.java
  src/main/java/com/dace/dmgr/system/CooldownManager.java
  src/main/java/com/dace/dmgr/system/command/LobbyCommand.java
  src/main/java/com/dace/dmgr/system/command/MenuCommand.java
  src/main/java/com/dace/dmgr/system/command/PlayerOptionCommand.java
  src/main/java/com/dace/dmgr/system/command/test/DummyCommand.java
  src/main/java/com/dace/dmgr/system/command/test/SelectCharCommand.java
  src/main/java/com/dace/dmgr/util/InventoryUtil.java
  src/main/java/com/dace/dmgr/util/LocationUtil.java
  src/main/java/com/dace/dmgr/util/VectorUtil.java
Labels: 🛠 Refactoring, 📄 Document

#71 #70 인터페이스 리팩토링
  src/main/java/com/dace/dmgr/combat/Bullet.java
  src/main/java/com/dace/dmgr/combat/Combat.java
  src/main/java/com/dace/dmgr/combat/CombatStatusEffect.java
  src/main/java/com/dace/dmgr/combat/CombatTick.java
  src/main/java/com/dace/dmgr/combat/Hitscan.java
  src/main/java/com/dace/dmgr/combat/Projectile.java
  src/main/java/com/dace/dmgr/combat/character/Character.java
  src/main/java/com/dace/dmgr/combat/character/ICharacter.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceA1.java
  src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java
  src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/combat/entity/ICombatEntity.java
  src/main/java/com/dace/dmgr/event/listener/OnEntityDeath.java
  src/main/java/com/dace/dmgr/gui/item/ButtonItem.java
  src/main/java/com/dace/dmgr/gui/item/CombatItem.java
  src/main/java/com/dace/dmgr/gui/item/DisplayItem.java
  src/main/java/com/dace/dmgr/gui/item/GuiItem.java
  src/main/java/com/dace/dmgr/system/HashMapList.java
  src/main/java/com/dace/dmgr/system/command/test/SelectCharCommand.java
Labels: 🛠 Refactoring, 📄 Document
