Repository dkdace/dmgr-server, pull requests merged in 2024-10, with the labels that each got.

#188 전투원 '체드' 추가
  src/main/java/com/dace/dmgr/combat/action/info/WeaponInfo.java
  src/main/java/com/dace/dmgr/combat/action/skill/StackableSkill.java
  src/main/java/com/dace/dmgr/combat/action/weapon/AbstractWeapon.java
  src/main/java/com/dace/dmgr/combat/action/weapon/Weapon.java
  src/main/java/com/dace/dmgr/combat/character/CharacterType.java
  src/main/java/com/dace/dmgr/combat/character/ched/Ched.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA1.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA1Info.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA2.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA2Info.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA3.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedA3Info.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedP1.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedP1Info.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedUlt.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedUltInfo.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedWeapon.java
  src/main/java/com/dace/dmgr/combat/character/ched/action/ChedWeaponInfo.java
  src/main/java/com/dace/dmgr/combat/character/inferno/action/InfernoA2.java
  src/main/java/com/dace/dmgr/combat/character/inferno/action/InfernoWeapon.java
  src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA2.java
  src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA3.java
  src/main/java/com/dace/dmgr/combat/character/jager/action/JagerUlt.java
  src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaA1.java
  src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaT1.java
  src/main/java/com/dace/dmgr/combat/character/silia/action/SiliaP2.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Burning.java
  src/main/java/com/dace/dmgr/combat/interaction/BouncingProjectile.java
  src/main/java/com/dace/dmgr/combat/interaction/Bullet.java
  src/main/java/com/dace/dmgr/event/EventManager.java
  src/main/java/com/dace/dmgr/event/listener/OnEntityShootBowEvent.java
  src/main/java/com/dace/dmgr/event/listener/OnPlayerInteract.java
  src/main/java/com/dace/dmgr/util/LocationUtil.java
  src/main/java/com/dace/dmgr/util/NamedSound.java
Labels: ➕ Feature/System, 🛠 Refactoring, ➕ Feature/Character

#190 신규 데스매치 맵 추가
  src/main/java/com/dace/dmgr/game/map/TeamDeathmatchMap.java
Labels: ➕ Feature/System

#192 궁극기 팩 추가
  src/main/java/com/dace/dmgr/GeneralConfig.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/game/Game.java
  src/main/java/com/dace/dmgr/util/NamedSound.java
Labels: ➕ Feature/System

#196 전투원 중복 선택 방지
  src/main/java/com/dace/dmgr/combat/character/CharacterType.java
  src/main/java/com/dace/dmgr/item/gui/SelectChar.java
Labels: ➕ Feature/System

#198 상태 효과 처리 리팩토링
  src/main/java/com/dace/dmgr/combat/action/AbstractAction.java
  src/main/java/com/dace/dmgr/combat/action/MeleeAttackAction.java
  src/main/java/com/dace/dmgr/combat/action/skill/AbstractSkill.java
  src/main/java/com/dace/dmgr/combat/action/weapon/AbstractWeapon.java
  src/main/java/com/dace/dmgr/combat/character/jager/action/JagerT1.java
  src/main/java/com/dace/dmgr/combat/character/vellion/Vellion.java
  src/main/java/com/dace/dmgr/combat/entity/CombatRestrictions.java
  src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
  src/main/java/com/dace/dmgr/combat/entity/module/DamageModule.java
  src/main/java/com/dace/dmgr/combat/entity/module/HealModule.java
  src/main/java/com/dace/dmgr/combat/entity/module/JumpModule.java
  src/main/java/com/dace/dmgr/combat/entity/module/MoveModule.java
  src/main/java/com/dace/dmgr/combat/entity/module/StatusEffectModule.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Grounding.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/HealBlock.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Invulnerable.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Silence.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Snare.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/StatusEffect.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/StatusEffectType.java
  src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Stun.java
  src/main/java/com/dace/dmgr/event/listener/OnPlayServerCustomSoundEffect.java
  src/main/java/com/dace/dmgr/event/listener/OnPlayServerNamedSoundEffect.java
Labels: 3️⃣ Priority: Normal, 🛠 Refactoring
